app/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import EntryList, SpecialtyViewSet, SchoolEntryList, SchoolPendingList, SchoolViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'schools', SchoolViewSet, basename='school')
router.register(r'entries', EntryList)
router.register(r'specialties', SpecialtyViewSet)
router.register(r'schools/(?P<pk>\d+)/entries', SchoolEntryList, basename='foooo/')
router.register(r'pending_schools', SchoolPendingList, basename='pending_schools')

urlpatterns = [
    path('', include(router.urls)),
]

app/excels/urls.py
from django.urls import path
from . import views


app_name = 'excels'

urlpatterns = [
    path('add_schools/', views.add_schools, name='add_schools'),
    path('add_specialties/', views.add_specialties, name='add_specialties'),
    path('excel_entries/', views.excel_entries, name='excel_entries'),
    path('excel_aggregated_entries/', views.excel_aggregated_entries, name='excel_aggregated_entries'),
    path('excel_history/', views.excel_history, name='excel_history'),
    path('excel_user_history/', views.excel_user_history, name='excel_user_history'),
]

app/history/urls.py
from django.urls import path
from .views import HistoryListView, UserHistoryListView
from . import views


app_name = 'history'

urlpatterns = [
    path('history/', HistoryListView.as_view(), name='history'),
    path('clear_history/', views.clear_history, name='clear_history'),
    path('user_history/', UserHistoryListView.as_view(), name='user_history'),
]

app/main_app/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SchoolViewSet, EntryViewSet, SpecialtyViewSet, SchoolEntryList

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'schools', SchoolViewSet)
router.register(r'entries', EntryViewSet)
router.register(r'specialties', SpecialtyViewSet)
router.register(r'schools/(?P<pk>\d+)/entries', SchoolEntryList, basename='foooo/')

urlpatterns = [
    path('', include(router.urls)),
]

app/main_app/urls.py
from django.urls import path, include
from .views import (
    EntriesListView,
    EntriesVacanciesListView,
    EntriesSurplusListView,
    UserEntriesListView,
    EntryDetailView,
    EntryCreateView,
    EntryUpdateView,
    EntryDeleteView,
    SpecialtiesListView,
)
from . import views


app_name = 'main_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('clear_entries/', views.clear_entries, name='clear_entries'),
    path('entries/', EntriesListView.as_view(), name='entries'),
    path('entries_vacancies/', EntriesVacanciesListView.as_view(), name='entries_vacancies'),
    path('entries_surplus/', EntriesSurplusListView.as_view(), name='entries_surplus'),
    path('user_entries/', UserEntriesListView.as_view(), name='user_entries'),
    path('entry/<int:pk>/', EntryDetailView.as_view(), name='entry_detail'),
    path('entry/new/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/<int:pk>/update/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='entry_delete'),
    path('about/', views.about, name='about'),
    path('help/', views.help, name='help'),
    path('specialties/', SpecialtiesListView.as_view(), name='specialties'),
]

app/pdfs/urls.py
from django.urls import path
from .views import (
    PdfUserEntries,
    PdfEntries,
    PdfHistory,
    PdfUserHistory
)


app_name = 'pdfs'

urlpatterns = [
    path('pdf_user_entries/', PdfUserEntries.as_view(), name='pdf_user_entries'),
    path('pdf_entries/', PdfEntries.as_view(), name='pdf_entries'),
    path('pdf_history/', PdfHistory.as_view(), name='pdf_history'),
    path('pdf_user_history/', PdfUserHistory.as_view(), name='pdf_user_history'),
]

app/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UserAuthenticationView
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('info/', views.info, name='info'),
    path('login/', UserAuthenticationView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

app/vacancies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls')),
    path('maskeparty/', include('impersonate.urls')),
    path('', include('main_app.urls')),
    path('', include('history.urls')),
    path('', include('users.urls')),
    path('', include('schools.urls')),
    path('', include('excels.urls')),
    path('', include('pdfs.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

app/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from schools.models import School


class Specialty(models.Model):
    code = models.CharField(unique=True, max_length=25, verbose_name=_('Ειδικότητα'))
    lectic = models.CharField(max_length=100, verbose_name=_('Λεκτικό'), blank=True)
    label = models.CharField(max_length=100, null=True, blank=True, verbose_name=_('Λεκτικό Εκτύπωσης'))
    active = models.BooleanField(default=True, verbose_name=_("Διαθέσιμο προς χρήση"))
    ordering = models.SmallIntegerField(null=True, verbose_name=_("Σειρά"))

    def __str__(self):
        return self.code


class EntryVariantType(models.TextChoices):
    
    GENERAL_EDUCATION = 'GENERAL_EDUCATION', _('Γενικής Αγωγής - μη Πανελλαδικώς Εξεταζόμενα Μαθήματα')
    GENERAL_EDUCATION_WITH_EXAMS = 'GENERAL_EDUCATION_WITH_EXAMS', _('Γενικής Αγωγής - Πανελλαδικώς '
                                                                     'Εξεταζόμενα Μαθήματα')
    SPECIFIC_NEEDS_SMEAE = 'SPECIFIC_NEEDS_SMEAE', _('Ειδικής Αγωγής - ΣΜΕΑΕ')
    SPECIFIC_NEEDS_INTEGRATION_CLASS = 'SPECIFIC_NEEDS_INTEGRATION_CLASS', _('Ειδικής Αγωγής - Τμήμα Ένταξης')
    SPECIFIC_NEEDS_INTEGRATION_CLASS_DEAF = 'SPECIFIC_NEEDS_INTEGRATION_CLASS_DEAF', _('Ειδικής Αγωγής - '
                                                                                       'Τμήμα Ένταξης Κωφών')
    SPECIFIC_NEEDS_INTEGRATION_CLASS_BLIND = 'SPECIFIC_NEEDS_INTEGRATION_CLASS_BLIND', _('Ειδικής Αγωγής - Τμήμα '
                                                                                         'Ένταξης Τυφλών')
    SPECIFIC_NEEDS_PARALLEL_SUPPORT = 'SPECIFIC_NEEDS_PARALLEL_SUPPORT', _('Ειδικής Αγωγής - Παράλληλης Στήριξης')
    SPECIFIC_NEEDS_PARALLEL_SUPPORT_DEAF = 'SPECIFIC_NEEDS_PARALLEL_SUPPORT_DEAF', _('Ειδικής Αγωγής - Παράλληλης '
                                                                                     'Στήριξης Κωφών')
    SPECIFIC_NEEDS_PARALLEL_SUPPORT_BLIND = 'SPECIFIC_NEEDS_PARALLEL_SUPPORT_BLIND', _('Ειδικής Αγωγής - Παράλληλης '
                                                                                       'Στήριξης Τυφλών')
    VULNERABLE_GROUP = 'VULNERABLE_GROUP', _('Ευπαθών Ομάδων')
    BY_RESIGNATION = 'BY_RESIGNATION', _('Από παραίτηση')
    RECEPTION_CLASSES = 'RECEPTION_CLASSES', _('Τάξεις Υποδοχής')
    A_NEW_START = 'A_NEW_START', _('Μ.Ν.Α.Ε.'),
    MUSICAL_AKORTEON = 'MUSICAL_AKORTEON', _('Ακορντεόν')
    MUSICAL_BIOLA = 'MUSICAL_BIOLA', _('Βιόλα')
    MUSICAL_BIOLI = 'MUSICAL_BIOLI', _('Βιολί')
    MUSICAL_BIOLI_TRADITIONAL = 'MUSICAL_BIOLI_TRADITIONAL', _('Βιολί (Παραδοσιακό)')
    MUSICAL_BIOLOTSELO = 'MUSICAL_BIOLOTSELO', _('Βιολοντσέλο')
    MUSICAL_GAINDA = 'MUSICAL_GAINDA', _('Γκάιντα')
    MUSICAL_DIEYTH_ORXISTRAS = 'MUSICAL_DIEYTH_ORXISTRAS', _('Διεύθυνση Ορχήστρας')
    MUSICAL_DIEYTH_XORODIAS = 'MUSICAL_DIEYTH_XORODIAS', _('Διεύθυνση Χορωδίας')
    MUSICAL_ZOURNAS = 'MUSICAL_ZOURNAS',  _('Ζουρνάς')
    MUSICAL_THEORHTIKA_BYZ_MOUSIKHS = 'MUSICAL_THEORHTIKA_BYZ_MOUSIKHS', _('Θεωρητικά Βυζαντινής Μουσικής')
    MUSICAL_THEORHTIKA_EYR_MOUSIKHS = 'MUSICAL_THEORHTIKA_EYR_MOUSIKHS', _('Θεωρητικά Ευρωπαϊκής Μουσικής')
    MUSICAL_KANONAKI = 'MUSICAL_KANONAKI', _('Κανονάκι')
    MUSICAL_KITHARA_HLEKTRIKI = 'MUSICAL_KITHARA_HLEKTRIKI', _('Κιθάρα ηλεκτρική')
    MUSICAL_KITHARA_KLASIKI = 'MUSICAL_KITHARA_KLASIKI', _('Κιθάρα κλασική')
    MUSICAL_KLARINETO = 'MUSICAL_KLARINETO',  _('Κλαρινέτο')
    MUSICAL_KLARINO_PARADOSIAKO = 'MUSICAL_KLARINO_PARADOSIAKO', _('Κλαρίνο (Παραδοσιακό)')
    MUSICAL_KONTRAMPASO = 'MUSICAL_KONTRAMPASO', _('Κοντραμπάσο')
    MUSICAL_KORNO = 'MUSICAL_KORNO', _('Κόρνο')
    MUSICAL_KROUSTA_EYR = 'MUSICAL_KROUSTA_EYR', _('Κρουστά Ευρωπαϊκά (Κλασικά - Σύγχρονα)')
    MUSICAL_KROUSTA_PARADOSIAKA = 'MUSICAL_KROUSTA_PARADOSIAKA', _('Κρουστά παραδοσιακά')
    MUSICAL_LAOUTO = 'MUSICAL_LAOUTO', _('Λαούτο')
    MUSICAL_LYRA_DODEKANHSOU = 'MUSICAL_LYRA_DODEKANHSOU', _('Λύρα Δωδεκανήσου')
    MUSICAL_LYRA_KRHTIKH = 'MUSICAL_LYRA_KRHTIKH', _('Λύρα Κρητική')
    MUSICAL_LYRA_MAKEDONIAS = 'MUSICAL_LYRA_MAKEDONIAS', _('Λύρα Μακεδονίας')
    MUSICAL_LYRA_POLITIKH = 'MUSICAL_LYRA_POLITIKH', _('Λύρα Πολίτικη')
    MUSICAL_LYRA_PONTIAKH = 'MUSICAL_LYRA_PONTIAKH', _('Λύρα Ποντιακή')
    MUSICAL_MANTOLINO = 'MUSICAL_MANTOLINO', _('Μαντολίνο')
    MUSICAL_MOUSIKHS_TEXNLOGIAS = 'MUSICAL_MOUSIKHS_TEXNLOGIAS', _('Μουσικής Τεχνολογίας (Εφαρμογές Η/Υ)')
    MUSICAL_MPASO_HLEKTRIKO = 'MUSICAL_MPASO_HLEKTRIKO', _('Μπάσο ηλεκτρικό')
    MUSICAL_MPOUZOUKI_TRIXORDO = 'MUSICAL_MPOUZOUKI_TRIXORDO', _('Μπουζούκι (Τρίχορδο)')
    MUSICAL_NEI_KABALI_PAR_AYLOI = 'MUSICAL_NEI_KABALI_PAR_AYLOI', _('Νέι-Καβάλι-Παραδοσιακοί Αυλοί')
    MUSICAL_OMPOE = 'MUSICAL_OMPOE', _('Όμποε')
    MUSICAL_OUTI = 'MUSICAL_OUTI', _('Ούτι')
    MUSICAL_PIANO = 'MUSICAL_PIANO',  _('Πιάνο')
    MUSICAL_SANTOURI = 'MUSICAL_SANTOURI', _('Σαντούρι')
    MUSICAL_SAXOFONO = 'MUSICAL_SAXOFONO', _('Σαξόφωνο (Άλτο - Βαρύτονο - Τενόρο)')
    MUSICAL_TAMPOURA = 'MUSICAL_TAMPOURA', _('Ταμπουράς')
    MUSICAL_TOUMPA = 'MUSICAL_TOUMPA', _('Τούμπα')
    MUSICAL_TROMPETA = 'MUSICAL_TROMPETA', _('Τρομπέτα')
    MUSICAL_TROMPONI = 'MUSICAL_TROMPONI', _('Τρομπόνι')
    MUSICAL_FAGOTO = 'MUSICAL_FAGOTO', _('Φαγκότο')
    MUSICAL_FLAOUTO = 'MUSICAL_FLAOUTO', _('Φλάουτο')


class Entry(models.Model):
    ENTRY_CHOICES = (
        ('Κενό', 'Κενό'),
        ('Πλεόνασμα', 'Πλεόνασμα')
    )
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='entries', null=True, default=None)
    specialty = models.ForeignKey(Specialty, on_delete=models.CASCADE, verbose_name='Ειδικότητα', null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    hours = models.IntegerField(default=0, validators=[MinValueValidator(1)],
                                error_messages={'min_value': "Η τιμή πρέπει να είναι μεγαλύτερη του 0."},
                                help_text="Η τιμή πρέπει να είναι μεγαλύτερη του 0.",
                                verbose_name='Ώρες')
    date_time = models.DateTimeField(auto_now=True, verbose_name='Χρονική σήμανση')
    type = models.CharField(default='Κενό', choices=ENTRY_CHOICES, 
                            max_length=9, verbose_name='Κενό / Πλεόνασμα')
    description = models.TextField(verbose_name='Παρατηρήσεις', blank=True,
                                   help_text='Καταχωρίστε τυχόν παρατηρήσεις που μπορεί να έχετε για το '
                                             'συγεκριμένο κενό/πλεόνασμα',
                                   default='')
    variant = models.CharField(
        max_length=64, 
        verbose_name=_('Τύπος Κενού / Πλεονάσματος'), 
        help_text=_('Επιλέξετε το είδος του κενού'),
        choices=EntryVariantType.choices,
        default=EntryVariantType.GENERAL_EDUCATION,
        null=False
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['owner', 'specialty', 'variant'], name='unique_variant_entry')
        ]

    def get_variant_label(self):
        try:
            return EntryVariantType(self.variant).label if self.variant else None
        except Exception:
            return None

    def validate_unique(self, exclude=None):
        qs = self.__class__.objects.filter(specialty=self.specialty, variant=self.variant)
        if self.pk is None:
            # we are not updating, so go ahead
            if qs.filter(owner=self.owner).exists():
                raise ValidationError({'variant': 
                                    _(f'Υπάρχει ήδη καταχωρισμένο κενό/πλεόνοσμα με αυτόν τον τύπο για '
                                      f'την ειδικότητα {self.specialty}')})
    
    def __str__(self):
        return f'{self.specialty} ({self.variant}) | {self.owner} | {self.hours} | {self.type} | {self.description}'

    def get_absolute_url(self):
        return reverse('main_app:entry_detail', kwargs={'pk': self.pk})

app/main_app/templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main_app/main.css' %}">

    {% if title %}
        <title>ΔΔΕ Ηρακλείου - {{ title }}</title>
    {% else %}
        <title>ΔΔΕ Ηρακλείου</title>
    {% endif %}
</head>
<body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'main_app:home' %}">ΔΔΕ Ηρακλείου / Εφαρμογή καταχώρισης κενών</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <!--
                    <a class="nav-item nav-link" href="{% url 'main_app:home' %}">Αρχική</a>
                    -->
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'users:info' %}">{{ user.username }}</a>
                        <a class="nav-item nav-link" href="{% url 'users:logout' %}">Αποσύνδεση</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'users:login' %}">Σύνδεση</a>
                        <a class="nav-item nav-link" href="{% url 'users:register' %}">Εγγραφή</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>


<div role="main" class="container-fluid">
    <div class="row">
        <div class="col-9 mx-auto">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags != 'error' %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-danger">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if is_school %}
                {% if school_updates_disallowed %}
                <div class="alert alert-danger">Προσωρινά έχει απενεργοποιηθεί η δυνατότητα καταχώρισης ή ενημέρωσης
                    στοιχείων απο τις σχολικές μονάδες</div>
                {% elif not user.profile.status %}
                <div class="alert alert-danger">Δεν έχετε κάνει επικαιροποίηση.</div>
                {% endif %}
            {% else %}
            {% if school_updates_disallowed %}
                <div class="alert alert-info">Οι σχολικές μονάδες δεν μπορούν να καταχωρήσουν ή να επεξεργαστούν
                    κενά/πλεονάσματα !
                </div>
            {% endif %}
            {% endif %}
            {% block content %}{% endblock %}

        </div>

        {% if user.is_authenticated %}
            {% if user.is_superuser %}
                <div class="col-md-3">
                    <ul class="list-group">
                        <!-- <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="/admin/">Διαχείριση Βάσης</a>
                        </li> -->
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'schools:clear_status' %}">Διαγραφή Επικαιροποιήσεων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:clear_entries' %}">Διαγραφή Καταχωρίσεων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'history:clear_history' %}">Διαγραφή Ιστορικού Καταχωρίσεων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                             <a class="sidebar-item" href="{% url 'excels:add_schools' %}">Ενημέρωση Σχολικών Μονάδων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                             <a class="sidebar-item" href="{% url 'excels:add_specialties' %}">Ενημέρωση Ειδικοτήτων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'schools:schools' %}">Προβολή Σχολικών μονάδων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:specialties' %}">Προβολή Ειδικοτήτων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:entries' %}">Προβολή Καταχωρίσεων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:entries_vacancies' %}">Προβολή Κενών</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:entries_surplus' %}">Προβολή Πλεονασμάτων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <span class="sidebar-item">
                                <a class="sidebar-item" href="{% url 'excels:excel_aggregated_entries' %}">Εξαγωγή
                                    καταχωρίσεων συγκεντρωτικά σε Excel</a>
                            </span>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <span class="sidebar-item">Εξαγωγή καταχωρίσεων σε
                                [ <a class="sidebar-item" href="{% url 'excels:excel_entries' %}">xlsx</a> |
                                <a class="sidebar-item" href="{% url 'pdfs:pdf_entries' %}">pdf</a> ]
                            </span>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'schools:check_schools' %}">Έλεγχος Χρηστών-Σχολικών
                                μονάδων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'schools:check_status' %}">Έλεγχος Επικαιροποιήσεων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'history:history' %}">Ιστορικό Αλλαγών</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <span class="sidebar-item">Εξαγωγή ιστορικού σε
                                [ <a class="sidebar-item" href="{% url 'excels:excel_history' %}">xlsx</a> |
                                <a class="sidebar-item" href="{% url 'pdfs:pdf_history' %}">pdf</a> ]
                            </span>
                        </li>
                    </ul>
                </div>
            {% else %}
                <div class="col-md-3">

                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'users:info' %}">Πληροφορίες για το Σχολείο</a>
                        </li>
                        {% if not school_updates_disallowed %}
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:entry_create' %}">Προσθήκη καταχώρισης</a>
                        </li>
                        {% endif %}

                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:user_entries' %}">Προβολή καταχωρίσεων</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'pdfs:pdf_user_entries' %}">Εκτύπωση καταχωρίσεων</a>
                        </li>
                        {% if not school_updates_disallowed %}
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'schools:status_update' %}">Επικαιροποίηση</a>
                        </li>
                        {% endif %}
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'history:user_history' %}">Ιστορικό Αλλαγών</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <span class="sidebar-item">Εξαγωγή ιστορικού σε
                                [ <a class="sidebar-item" href="{% url 'excels:excel_user_history' %}">xlsx</a> |
                                <a class="sidebar-item" href="{% url 'pdfs:pdf_user_history' %}">pdf</a> ]
                            </span>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:help' %}">Εγχειρίδιο Χρήσης</a>
                        </li>
                        <li class="list-group-item list-group-item-light sidebar">
                            <a class="sidebar-item" href="{% url 'main_app:about' %}">Σχετικά με την εφαρμογή</a>
                        </li>
                    </ul>



                </div>
            {% endif %}
        {% endif %}
        {% block content-section %}{% endblock %}
    </div>
</div>


</body>
</html>

app/main_app/templates/main_app/entry_update.html
{% extends "main_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Ενημέρωση καταχώρισης για την ειδικότητα {{ entry.specialty }}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Καταχώριση</button>
                <a class="btn btn-outline-secondary" href="{% url 'main_app:user_entries' %}">Επιστροφή</a>
            </div>
        </form>
    </div>
{% endblock content %}