app/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import EntryList, SpecialtyViewSet, SchoolEntryList, SchoolPendingList, SchoolViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'schools', SchoolViewSet, basename='school')
router.register(r'entries', EntryList)
router.register(r'specialties', SpecialtyViewSet)
router.register(r'schools/(?P<pk>\d+)/entries', SchoolEntryList, basename='foooo/')
router.register(r'pending_schools', SchoolPendingList, basename='pending_schools')

urlpatterns = [
    path('', include(router.urls)),
]

app/main_app/urls.py
from django.urls import path, include
from .views import (
    EntriesListView,
    EntriesVacanciesListView,
    EntriesSurplusListView,
    UserEntriesListView,
    EntryDetailView,
    EntryCreateView,
    EntryUpdateView,
    EntryDeleteView,
    SpecialtiesListView,
)
from . import views


app_name = 'main_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('clear_entries/', views.clear_entries, name='clear_entries'),
    path('entries/', EntriesListView.as_view(), name='entries'),
    path('entries_vacancies/', EntriesVacanciesListView.as_view(), name='entries_vacancies'),
    path('entries_surplus/', EntriesSurplusListView.as_view(), name='entries_surplus'),
    path('user_entries/', UserEntriesListView.as_view(), name='user_entries'),
    path('entry/<int:pk>/', EntryDetailView.as_view(), name='entry_detail'),
    path('entry/new/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/<int:pk>/update/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='entry_delete'),
    path('about/', views.about, name='about'),
    path('help/', views.help, name='help'),
    path('specialties/', SpecialtiesListView.as_view(), name='specialties'),
]

app/schools/urls.py
from django.urls import path
from . import views
from .views import SchoolsListView, SchoolDetailView, SchoolClassesInfoCreateOrUpdateView


app_name = 'schools'

urlpatterns = [
    path('check_schools/', views.check_schools, name='check_schools'),
    path('schools/', SchoolsListView.as_view(), name='schools'),
    path('school/<int:pk>/', SchoolDetailView.as_view(), name='school_detail'),
    path('status_update/', views.status_update, name='status_update'),
    path('check_status/', views.check_status, name='check_status'),
    path('clear_status/', views.clear_status, name='clear_status'),
    path('school_class_info/update/', SchoolClassesInfoCreateOrUpdateView.as_view(), name='manage_school_class_info'),
]

app/vacancies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls')),
    path('maskeparty/', include('impersonate.urls')),
    path('', include('main_app.urls')),
    path('', include('history.urls')),
    path('', include('users.urls')),
    path('', include('schools.urls')),
    path('', include('excels.urls')),
    path('', include('pdfs.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

app/history/models.py
from django.db import models
from django.contrib.auth.models import User
from main_app.models import Specialty
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from main_app.models import EntryVariantType

class HistoryEntry(models.Model):
    ENTRY_CHOICES = (
        ('Κενό', 'Κενό'),
        ('Πλεόνασμα', 'Πλεόνασμα')
    )

    specialty = models.ForeignKey(Specialty, on_delete=models.CASCADE, verbose_name='Ειδικότητα', null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    hours = models.IntegerField(default=0)
    date_time = models.DateTimeField(default=now, verbose_name='Χρονική σήμανση')
    type = models.CharField(default='Κενό', choices=ENTRY_CHOICES, max_length=9, verbose_name='Κενό / Πλεόνασμα')
    description = models.TextField(verbose_name='Παρατηρήσεις', blank=True, default='')
    variant = models.CharField(
        max_length=64, 
        verbose_name=_('Τύπος Κενού / Πλεονάσματος'), 
        help_text=_('Επιλέξετε το είδος του κενού'), 
        choices=EntryVariantType.choices,
        default=EntryVariantType.GENERAL_EDUCATION,
        null=False
    )

    def __str__(self):
        return f'{self.specialty} | {self.owner} | {self.hours} | {self.type} | {self.description}'

app/schools/forms.py
from django import forms
from .models import SchoolClassesInfo

class SchoolClassesInfoUpdateForm(forms.ModelForm):

    # variant = forms.ChoiceField(
    #     label=_('Τύπος Κενού / Πλεονάσματος'),
    #     help_text=_('Επιλέξετε το είδος του κενού'),
    # )

    class Meta:
        model = SchoolClassesInfo
        fields = [
            'a_grade_classes',
            'a_grade_classes_over_21',
            'a_grade_classes_french',
            'a_grade_classes_german',
            'b_grade_classes',
            'b_grade_classes_over_21',
            'b_grade_classes_french',
            'b_grade_classes_german',
            'b_grace_classes_prosanatolismou',
            'b_grace_classes_anthropistikon',
            'c_grade_classes',
            'c_grade_classes_over_21',
            'c_grade_classes_french',
            'c_grade_classes_german',
            'c_grade_classes_prosanatolismou',
            'c_grade_classes_anthropistikon',
            'c_grade_classes_thetikon',
            'c_grade_classes_pliroforikis',
        ]
        exclude = [ 'school', ]
        # widgets = {
        #     'type': forms.RadioSelect,
        #     'description': forms.Textarea(attrs={'rows': 3}),
        # }

app/schools/views.py
import datetime
import logging
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.core.mail import BadHeaderError, send_mail, send_mass_mail
from django.conf import settings
from tabulate import tabulate
from constance import config
from django.utils import timezone
from django.utils.formats import date_format
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test, login_required
from django.views.generic import ListView, DetailView
from .models import School
from users.models import Profile, User
from main_app.models import Entry, EntryVariantType
from vacancies.decorators import block_if_templated
from vacancies.commons import school_updates_disallowed
from vacancies.utils.permissions import check_user_is_superuser


class SchoolDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = School

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.object is not None:
            current_school: School = self.object

            try:
                managed_by: Profile = current_school.managed_by
                data['is_finalized'] = managed_by.status is True
                data['finalized_on'] = managed_by.status_time
            except School.managed_by.RelatedObjectDoesNotExist:
                data['is_finalized'] = False
                data['finalized_on'] = None

            data['school_entries'] = Entry.objects.filter(school=current_school).order_by('specialty')
        return data

    def test_func(self):
        return check_user_is_superuser(self.request.user)


class SchoolsListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = School
    template_name = 'schools/schools.html'
    context_object_name = 'schools'
    ordering = ['name']
    paginate_by = 10

    def test_func(self):
        return check_user_is_superuser(self.request.user)


@login_required
@user_passes_test(check_user_is_superuser)
def check_schools(request):

    superusers = User.objects.filter(is_superuser=True)
    p_verified_users = Profile.objects.filter(verified=True).exclude(user__in=superusers)
    p_not_verified_users = Profile.objects.filter(verified=False).exclude(user__in=superusers)
    not_connected_schools = School.objects.filter(managed_by=None)

    return render(request, 'schools/check_schools.html', {'p_verified_users': p_verified_users,
                                                          'p_not_verified_users': p_not_verified_users,
                                                          'not_connected_schools': not_connected_schools,
                                                          })



@login_required
@block_if_templated(condition_func=school_updates_disallowed, template_name='main_app/action_blocked.html')
def status_update(request):
    if request.method == 'POST':

        user: User = request.user
        profile: Profile = user.profile
        school: School = profile.school
        utc_now = timezone.now()
        logging.info("school '%s' is trying to confirm data", school)

        profile.status = True
        profile.status_time = utc_now
        profile.save()
        if config.SEND_FINALIZATION_EMAILS is True:
            try:

                user_model_class = get_user_model()
                users = user_model_class.objects.filter(is_superuser=True)

                recipient_list = [user.email for user in users]
                logging.info("we will also notify via email the following users : %s", recipient_list)

                entries = Entry.objects.filter(school=school).order_by('specialty')
                headers = ['Ειδικότητα', 'Τύπος', 'Είδος', 'Ώρες']
                values = [(f'{entry.specialty.code} - {entry.specialty.lectic}', entry.type,
                           str(EntryVariantType(entry.variant).label), entry.hours) for entry in entries]

                entries_table = tabulate(tabular_data=values, headers=headers, tablefmt='simple_grid')
                status_time_localized = date_format(profile.status_time, format='SHORT_DATETIME_FORMAT', use_l10n=True)
                subject = f'{settings.EMAIL_SUBJECT_PREFIX}- Επικαιροποίηση Σχολικής Μονάδας \'{school.name}\''
                message = f'Σας ενημερώνουμε πως η σχολική μονάδα \'{school.name}\' επικαιροποιήθηκε επιτυχώς απο ' \
                          f'τον χρήστη \'{user.username}\' ως προς τα κενά και τα πλεονάσματά της στις ' \
                          f'\'{status_time_localized}\'.\n\n Τα επικαιροποιημένα στοιχεία κενών/πλεονασμάτων της μονάδας ' \
                          f'είναι τα παρακάτω :\n\n' + entries_table + f'\n\n\nΗ ειδοποίηση είναι μια αυτοματοποίηση ' \
                                                                       'του τμήματος Δ\' της ΔΔΕ Ηρακλείου'

                for recipient in recipient_list:
                    send_mail(
                        subject=subject,
                        message=message,
                        from_email=settings.DEFAULT_FROM_EMAIL,
                        fail_silently=True,
                        recipient_list=(recipient, )
                    )

            except Exception as e:
                logging.error("failed to notify users via email due to '%s'", str(e))
        else:
            logging.info("SEND_FINALIZATION_EMAILS is false, not sending finalization update")

        logging.info("school '%s' successfully confirmed data on '%s'", school, utc_now)

        return redirect('users:info')
    else:
        if request.user.profile.verified:
            return render(request, 'schools/status_update.html', {})
        else:
            return render(request, 'main_app/not_verified.html', {})


@login_required
@user_passes_test(check_user_is_superuser)
def check_status(request):

    # superusers = User.objects.filter(is_superuser=True)
    # p_status_true = Profile.objects.filter(status=True).exclude(user__in=superusers)
    # u_status_false = User.objects.filter(profile__status=False).exclude(pk__in=superusers).exclude(profile__verified=False)
    # s_status_false = School.objects.filter(email__in=[u.email for u in u_status_false])
    # s_status_false = School.objects.filter(email__in=[u.email for u in u_status_false])
    s_status_true = School.objects.filter(managed_by__status=True).order_by('-managed_by__status_time')
    s_status_false = School.objects.filter(managed_by__status=False).order_by('name')

    return render(request, 'schools/check_status.html', {'s_status_true': s_status_true,
                                                         's_status_false': s_status_false,
                                                         })


@login_required
@user_passes_test(check_user_is_superuser)
def clear_status(request):
    if request.method == 'POST':
        Profile.objects.all().update(status=False, status_time=None)
        return redirect('schools:check_status')
    else:
        return render(request, 'schools/clear_status.html')


app/schools/templates/schools/check_schools.html
{% extends "main_app/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <h3 class="article-title">Έλεγχος Χρηστών-Σχολικών μονάδων</h3>
        </div>
    </article>

    <article class="media content-section">
        <div class="media-body">
            <ul style="list-style-type:none; padding: 0;">
                <li class="alert alert-success" style="margin: 1px;">
                    Χρήστες-Σχολικές μονάδες που έχουν επαληθευτεί: {{ p_verified_users|length }}
                </li>
                <li class="alert alert-danger" style="margin: 1px;">
                    Σχολικές μονάδες που δεν έχουν συνδεθεί με χρήστη: {{ not_connected_schools|length }}
                </li>
            </ul>
        </div>
    </article>

    {% if p_verified_users|length != 0 %}
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-title">Χρήστες-Σχολικές μονάδες που έχουν επαληθευτεί</h4>
                <div>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <td>
                                <nobr>Α/Α</nobr>
                            </td>
                            <td>Σχολείο</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for p in p_verified_users %}
                            <tr>
                                <td> {{ forloop.counter }} </td>
                                <td> {{ p.user.last_name }} </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
    {% endif %}

    {% if not_connected_schools|length != 0 %}
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-title">Σχολικές μονάδες που δεν έχουν συνδεθεί με χρήστη</h4>
                <div>
                    <table class="table table-hover table-sm">
                        <thead class="thead-light">
                            <tr>
                                <th>
                                    <nobr>Α/Α</nobr>
                                </th>
                                <th>Σχολείο</th>
                                <th>Διευθυντής</th>
                                <th>Τηλέφωνο</th>
                                <th>Πληροφορίες</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for s in not_connected_schools %}
                            <tr>
                                <td> {{ forloop.counter }} </td>
                                <td> {{ s.name}}</td>
                                <td> {{ s.principal|default:'-'|truncatechars:30 }} </td>
                                <td> {{ s.phone|default:'-'|truncatechars:13 }} </td>
                                <td style="text-align: center">
                                    <a href="{% url 'schools:school_detail' s.id %}">
                                        <button type="button" class="btn btn-success btn-sm mt-1 mb-1" aria-label="Left Align" 
                                        data-toggle="tooltip" data-placement="top" title="Πληροφορίες Σχολικής Μονάδας">
                                            <span class="bi-info" aria-hidden="true"></span>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
    {% endif %}

    {% if p_not_verified_users|length != 0 %}
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-title">Χρήστες που έχουν κάνει εγγραφή αλλά δεν έχουν επαληθευτεί</h4>
                <div>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <td>
                                <nobr>Α/Α</nobr>
                            </td>
                            <td>Χρήστης</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for p in p_not_verified_users %}
                            <tr>
                                <td> {{ forloop.counter }} </td>
                                <td> {{ p.user }} </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
    {% endif %}
{% endblock content %}

app/schools/templates/schools/check_status.html
{% extends "main_app/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <h3 class="article-title">Έλεγχος Επικαιροποιήσεων</h3>
        </div>
    </article>
    {% if s_status_true|length != 0 %}
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-title">Σχολικές μονάδες που έχουν κάνει επικαιροποίηση</h4>
                <div>
                    <table class="table table-hover table-sm">
                        <thead class="thead-light">
                        <tr>
                            <th>
                                <nobr>Α/Α</nobr>
                            </th>
                            <th>Σχολείο</th>
                            <th>email</th>
                            <th>Διευθυντής</th>
                            <th>Τηλέφωνο</th>
                            <th>Ημ/νια Επικαιρ.</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for s in s_status_true %}
                            <tr>
                                <td> {{ forloop.counter }} </td>
                                <td>
                                    <a href="{% url 'schools:school_detail' s.id %}">{{ s.name}}</a>
                                </td>
                                <td>
                                    <a href="mailto:{{s.email}}"><code>{{s.email}}</code></a>
                                </td>
                                <td> {{ s.principal|default:'-'|truncatechars:30 }} </td>
                                <td> {{ s.phone|default:'-'|truncatechars:13 }} </td>
                                <td>
                                    <strong>{{s.managed_by.status_time|date:'Y-m-d H:i' }}</strong>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
    {% endif %}

    {% if s_status_false|length != 0 %}
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-title">Σχολικές μονάδες που δεν έχουν κάνει επικαιροποίηση</h4>
                <div>
                    <table class="table table-hover table-sm">
                        <thead class="thead-light">
                        <tr>
                            <th>
                                <nobr>Α/Α</nobr>
                            </th>
                            <th>Σχολείο</th>
                            <th>email</th>
                            <th>Διευθυντής</th>
                            <th>Τηλέφωνο</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for s in s_status_false %}
                            <tr>
                                <td> {{ forloop.counter }} </td>
                                <td>
                                    <a href="{% url 'schools:school_detail' s.id %}">{{ s.name}}</a>
                                </td>
                                <td>
                                    <a href="mailto:{{s.email}}"><code>{{s.email}}</code></a>
                                </td>
                                <td> {{ s.principal|default:'-'|truncatechars:30 }} </td>
                                <td> {{ s.phone|default:'-'|truncatechars:13 }} </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
    {% endif %}
{% endblock content %}

app/schools/templates/schools/class_info_update.html
{% extends "main_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Ενημέρωση Τμημάτων Σχολικής Μονάδας {{ school.name }}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Καταχώριση</button>
                <a class="btn btn-outline-secondary" href="{% url 'main_app:user_entries' %}">Επιστροφή</a>
            </div>
        </form>
    </div>
{% endblock content %}

app/schools/templates/schools/school_detail.html
{% extends "main_app/base.html" %}
{% block content %}
<div class="content-section">
    <h3>Πληροφορίες για το "{{ school.name }}"</h3>
    <br/>
    {% if is_finalized %}
    <div class="alert alert-success">Η σχολική μονάδα έχει επικαιροποιήσει επιτυχώς στις {{
        finalized_on|date:'Y-m-d@H:i' }}
    </div>
    {% else %}
    <div class="alert alert-danger">H σχολική μονάδα ΔΕΝ έχει επικαιροποιήσει τα κενά/πλεονάσματα της</div>
    {% endif %}
    <table class="table table-sm">
        <tbody>
        <tr>
            <td style="width: 40%">Κωδικός Υπουργείου</td>
            <td>{{ school.ministry_code|default:'-' }}</td>
        </tr>
        <tr>
            <td style="width: 40%">Ονομασία</td>
            <td>{{ school.name }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td><a href="mailto:{{ school.email }}"><code>{{ school.email }}</code></a></td>
        </tr>
        <tr>
            <td>Διευθυντής</td>
            <td>{{ school.principal }}</td>
        </tr>
        <tr>
            <td>Τηλέφωνο</td>
            <td>{{ school.phone }}</td>
        </tr>
        <tr>
            <td>Διεύθυνση</td>
            <td>{{ school.address }}</td>
        </tr>
        <tr>
            <td>Έχει συνδεθεί με χρήστη</td>
            <td>
                {% if school.managed_by %}
                Ναι
                {% else %}
                Όχι
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>

    {% if school.school_type in classes_info_allowed_school_types %}
    <br/>
    <h5>Κατάσταση Τάξεων & Τμημάτων</h5>
    <br/>

    {% if school.classes_info %}
    <table class="table table-sm">
        <tbody>
        <tr>
            <td style="width: 40%">Συνολικά Τμήματα Α' Τάξης</td>
            <td style="font-weight: bold">{{ school.classes_info.a_grade_classes|default:'0' }}</td>
            <td style="width: 40%">Τμήματα Α' Τάξης με πάνω απο 21 μαθητές</td>
            <td style="font-weight: bold">{{ school.classes_info.a_grade_classes_over_21|default:'0' }}</td>
        </tr>
        <tr>
            <td style="width: 40%">Συνολικά Τμήματα B' Τάξης</td>
            <td style="font-weight: bold">{{ school.classes_info.b_grade_classes|default:'0' }}</td>
            <td style="width: 40%">Τμήματα Β' Τάξης με πάνω απο 21 μαθητές</td>
            <td style="font-weight: bold">{{ school.classes_info.b_grade_classes_over_21|default:'0' }}</td>
        </tr>
        <tr>


            <td style="width: 40%">Συνολικά Τμήματα Γ' Τάξης</td>
            <td style="font-weight: bold">{{ school.classes_info.c_grade_classes|default:'0' }}</td>
            <td style="width: 40%">Τμήματα Γ' Τάξης με πάνω απο 21 μαθητές</td>
            <td style="font-weight: bold">{{ school.classes_info.c_grade_classes_over_21|default:'0' }}</td>
        </tr>
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-danger">H σχολική μονάδα ΔΕΝ έχει ορίσει στοιχεία τμημάτων</div>
    {% endif %}

    <br/>
    {% endif %}

    <h5>Τρέχουσες Καταχωρίσεις</h5>
    <br/>
    <table class="table table-hover table-sm">
        <thead class="thead-light">
        <tr>
            <th scope="col">Ειδικότητα</th>
            <th scope="col">Τύπος Κατ.</th>
            <th scope="col">Είδος</th>
            <th scope="col">Ώρες</th>
            <th scope="col">Παρατηρήσεις</th>
            <th scope="col">Ημ/νια Καταχ.</th>
        </tr>
        </thead>
        <tbody>
        {% for entry in school_entries %}
        <tr>
            <td> {{ entry.specialty.code }}</td>
            <td>{{ entry.type }}</td>
            <td>{{ entry.get_variant_display }}</td>
            <td> {{ entry.hours }}</td>
            <td data-toggle="tooltip" data-placement="left" title="{{entry.description|default:''}}">
                {{ entry.description|default:'-'|truncatechars:10 }}
            </td>
            <td> {{ entry.date_time|date:'Y-m-d@H:i' }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}

app/schools/templates/schools/schools.html
{% extends "main_app/base.html" %}
{% block content %}
    <h3>Σχολικές μονάδες</h3>

    <table class="table table-hover table-sm">
        <thead class="thead-light">
            <tr>
                <th>Κωδ.</th>
                <th>Σχολείο</th>
                <th>Email</th>
                <th>Διευθυντής</th>
                <th>Τηλέφωνο</th>
                <th>Πληροφορίες</th>
            </tr>
        </thead>
        <tbody>
        {% for school in schools %}
            <tr>
                <td> {{ school.ministry_code|default:'-' }} </td>
                <td> {{ school.name }} </td>
                <td> <a href="mailto:{{ school.email }}"><code>{{ school.email }}</code></a></td>
                <td> {{ school.principal|default:'-'|truncatechars:25 }} </td>
                <td> {{ school.phone|default:'-'|truncatechars:13 }} </td>
                <td style="text-align: center">
                    <a href="{% url 'schools:school_detail' school.id %}">
                        <button type="button" class="btn btn-success btn-sm mt-1 mb-1" aria-label="Left Align" 
                        data-toggle="tooltip" data-placement="top" title="Πληροφορίες Σχολικής Μονάδας">
                            <span class="bi-info" aria-hidden="true"></span>
                        </button>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">Αρχή</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Προηγούμενη</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Επόμενη</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Τέλος</a>
        {% endif %}

    {% endif %}
{% endblock content %}

app/schools/templates/schools/status_update.html
{% extends "main_app/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Επικαιροποίηση</legend>
                Μπορείτε να κάνετε επικαιροποίηση, όταν σας ζητηθεί από τη ΔΔΕ, εφόσον:
                <ul>
                    <li>Δεν έχετε να δηλώσετε κανένα κενό/πλεόνασμα.</li>
                    <li>Έχετε κάνει έλεγχο των καταχωρίσεων σας και ανταποκρίνονται στην εικόνα του σχολείου
                        σας.
                    </li>
                </ul>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Ναι, κάνε επικαιροποίηση</button>
                <a class="btn btn-outline-secondary"
                   href="{% url 'main_app:user_entries' %}">Επιστροφή</a>
            </div>
        </form>
    </div>
{% endblock content %}